# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PyGOM documentation
author: Public Health England / UK Health Security Agency
#TODO change logo
logo: logo_pygom.jpg

# build files in table of contents
# used as alternative to exclude patterns
only_build_toc_files: true

# cache notebook outputs to save time
# TODO check what is required for readthedocs 
# this could avoid the issue of execution timing out
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: cache

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: pygom-book.tex

# Add a bibtex file so that we can create citations
# use sphinx to specify style

sphinx:
  extra_extensions:
  - 'sphinxcontrib.bibtex'

sphinx:
  config:
    bibtex_reference_style: author_year
    # TODO change md to bibtex
    bibtex_bibfiles: ref.bib

#bibtex_bibfiles: 
#  - ref.bib

sphinx:  
  extra_extensions:
  #- 'sphinx.ext.doctest'
  - 'sphinx.ext.autodoc'    
  - 'sphinx.ext.napoleon'
  - 'sphinx.ext.viewcode'
  - 'sphinx.ext.autosummary'
  config:
    add_module_names: True 
    autosummary_generate: True

#sphinx:
#  extra_extensions:
#  - 'sphinx.ext.autosummary'
#  config:
#    autosummary_generate: True

#sphinx:
#  extra_extensions:
#  - 'sphinx.ext.graphvizconfig'
  

# Information about where the book exists on the web
repository:
  url: https://github.com/ukhsa-collaboration/pygom  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
