# specify the language and which version
language: python

branches:
  only:
    - install-fix-docs

python:
  - 3.5
  - 3.6
  - 3.7
  - 3.8

before_install:
  - pip install -U pip

install:
  - pip install -r requirements.txt
  - python setup.py build
  - python setup.py install
  - pip install doc/requirements.txt

# Runs test with coverage
script:
  - cd doc; make html linkcheck