name: deploy-book

# only run when specific files change
# only run on install-fix-docs branch 
# TODO change this to dev/main branch once integrated
# TODO edit filepath once filepath levels are corrected

on:
  push:
    branches:
    - install-fix-docs
    paths: 
    - doc/**

jobs:
    deploy-book:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            # install python
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                python-version: 3.8

            # install dependencies
            - name: Install dependencies
              run: |
                pip install -r doc/doc/pygom-doc/requirements.txt

            # build the book
            - name: Build the book
              run: |
                jupyter-book build doc/doc/pygom-doc

            # deploy book to github-pages
            - name: GitHub Pages 
              uses: peaceiris/actions-gh-pages@v3.6.1
              with:
                publish_dir: doc/doc/pygom-doc/_build/html

